### ISSUE TITLE
Appinst: error logging and permissions and feature request

### ISSUE THREAD

**Issue by Wh0ba** [angelXwind/AppSync#37]
1 - there is a feature in ipainstaller which logs the full error if there is any 
i.e installing an iPad app on an iPhone , installing an app on an unsupported iOS version 
and it's very useful to understand why the install fails 

2 - set the tmp folder permissions to be deleted by all so when we run appinst as root then we run it as mobile we shouldn't have the "failed to remove the temporary folder" thing 

3 - adding a force install mode just like ipainstaller which forces the ipa to be installed no matter what errors occur (except for the binaries not being signed/fakesigned )

4 - adding a quite mode so nothing pops up except for errors

i'm sorry if i should make multiple issues or just summing them in one 
and thanks

**Comment by Mexicool** [comment]
![image](https://user-images.githubusercontent.com/78887972/110749497-1178cf00-81f6-11eb-91cc-8d81d28255fe.png)

**Comment by mrwags** [comment]
Version

**Comment by dlevi309** [comment]
@Wh0ba idek if you’re still interested in this, but installd in iOS13+ has a class that allows the iPad app installation stuff, here’s the [code](https://github.com/dlevi309/skipDeviceFamilyCheck). If you install it as a tweak, appinst is able to install iPad apps with no changes to the codebase.

**Comment by Hophoang** [comment]
Dddrytf4

**Comment by Hophoang** [comment]
java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:222)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:80)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Hophoang** [comment]
java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:222)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:80)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Hophoang** [comment]
Akgwyts
